# Generated by Django 5.1.2 on 2024-10-26 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUser', models.CharField(max_length=100)),
                ('senhaUser', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Citacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginCadastro.user')),
            ],
        ),
    ]
